// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:untitled7/common/app_images.dart';
import 'package:untitled7/model/question_answer.dart';

class Choice {
  const Choice({
    required this.questionAndAnswer,
    required this.title,
    required this.image,
  });
  final String title;  
  final String image;
  final List<QuestionAndAnswer> questionAndAnswer; 
}  
 
List<Choice> choices = [  
  Choice(
    title: "Văn học", 
    image: literatureImage, 
    questionAndAnswer: [
      QuestionAndAnswer(
        numberQuestion: 0, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 1, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 2, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 3, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 4, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 5, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
    ],),
  Choice(
    title: "Thể thao", 
    image: sportImage, 
    questionAndAnswer: [
      QuestionAndAnswer(
        numberQuestion: 0, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 1, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 2, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 3, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 4, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 5, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
    ]),
  Choice(
    title: "Toán học", 
    image: mathImage, 
   questionAndAnswer: [
      QuestionAndAnswer(
        numberQuestion: 0, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 1, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 2, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 3, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 4, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 5, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
    ]),
  Choice(
    title: "Lịch sử", 
    image: historyImage, 
     questionAndAnswer: [
      QuestionAndAnswer(
        numberQuestion: 0, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 1, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 2, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 3, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 4, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 5, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
    ]),
  Choice(
    title: "Khoa học", 
    image: scienceImage, 
    questionAndAnswer: [
      QuestionAndAnswer(
        numberQuestion: 0, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 1, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 2, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 3, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 4, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 5, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
    ]),
  Choice(
    title: "Âm nhạc", 
    image: musicImage, 
    questionAndAnswer: [
      QuestionAndAnswer(
        numberQuestion: 0, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 1, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 2, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 3, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 4, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 5, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 6, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 7, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
      QuestionAndAnswer(
        numberQuestion: 8, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 9, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 10, 
        question: "Tác giả của văn bản Cổng trường mở ra là ai?", 
        answerA: "Tô Hoài", 
        answerB: "Khánh Hoài", 
        answerC: "Nam Cao", 
        answerD: "Lí Lan", 
        answerRight: "Lí Lan"),
      QuestionAndAnswer(
        numberQuestion: 11, 
        question: "Tác phẩm nào sau đây KHÔNG phải của nhà văn Nam Cao?", 
        answerA: "Lão Hạc", 
        answerB: "Chí Phèo", 
        answerC: "Tắt đèn", 
        answerD: "Sống Mòn", 
        answerRight: "Tắt đèn"),
    ]),
];  